### ISSUE TITLE
和dnsmasq-full冲突

### ISSUE THREAD

**Issue by nobk** [mchome/luci-app-vlmcsd#1]
在选了dnsmasq-full包的选项时，luc-app-vlmcsd依然会选上dnsmasq包，由于dnsmasq-full和dnsmasq两者不能共存，导致编译失败。
建议把dnsmasq的依赖声明去掉吧，用lede/openwrt的差不多都会装dnsmasq不用特意设置。

**Comment by mchome** [comment]
ok
